# Generated by Django 4.0.3 on 2022-03-01 15:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('units', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialUnitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_Px_ugx', models.PositiveIntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DENIED', 'Denied'), ('FULFILLED', 'Fulfilled')], default=None, max_length=32, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materials.material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materials.material')),
            ],
        ),
    ]
