# Generated by Django 4.0.3 on 2022-03-13 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_rename_unit_px_ugx_materialunitprice_amount_ugx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequestlog',
            name='date_requested',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
