# Generated by Django 4.0.3 on 2022-03-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_materialrequestlog_date_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequestlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DENIED', 'Denied'), ('FULFILLED', 'Fulfilled')], default='PENDING', max_length=32, null=True),
        ),
    ]
